### ISSUE TITLE
acccmip6: command not found

### ISSUE THREAD

**Issue by tomorrgod** [TaufiqHassan/acccmip6#1]
hello , do you know this problem? ****acccmip6: command not found(when i input "acccmip6 -h" in ubuntu)

**Comment by TaufiqHassan** [comment]
Hi, 

I assume you've installed via pip? Make sure that you have python >3.5. You can also install the package via conda:

conda install -c thassan acccmip6

Taufiq

**Comment by tomorrgod** [comment]
thanks.I have solved the problem. i have the problem just because i use fish(acccmip6 just good for bash🤣).
