### ISSUE TITLE
Download by mask

### ISSUE THREAD

**Issue by rafaelcavalcantii** [TaufiqHassan/acccmip6#11]
Hi, 

does it has the functionality to download by mask? I could not find a proper way to do it directly.

For instance if I want to download the data from a specific region, some websites (such as [Copernicus](https://cds.climate.copernicus.eu/cdsapp#!/dataset/projections-cmip6?tab=form)) allow me to choose a geographical area and download the data only within the extension I want.

**Comment by TaufiqHassan** [comment]
Hi Rafael,

This can be a useful feature (for regional/local studies, reduced data size, faster downloads). Unfortunately, `acccmip6` only mimics the options in [ESGF](https://esgf-node.llnl.gov/search/cmip6/). I am not aware of any options in ESGF like in Copernicus for sub-region extraction. I could be wrong, but I believe Copernicus preprocess (regional masking) the data on their server. For now, `acccmip6`  only allows global data downloads, which can be pre-processed using [cmpdata](https://github.com/TaufiqHassan/cmpdata).

Best,
Taufiq

**Comment by rafaelcavalcantii** [comment]
Ok! Thank you very much for the reply. 
Great work by the way!
