### ISSUE TITLE
Dataset EC-Earth3 couldn't be retrieved.

### ISSUE THREAD

**Issue by at123456789x** [TaufiqHassan/acccmip6#12]
Hello!

 I couldn't download dataset   EC-Earth3 by acccmip6 recent days, even I get success about a month ago. However, the dataset can be found in official website.

Command of it like so:
`acccmip6 -o D -m EC-Earth3 -e historical,ssp126,ssp245,ssp370,ssp585 -v pr -f day -rlzn 1 -dir /cmip/pr -skip 1p2,1f2`

Thanks,
wangq

**Comment by TaufiqHassan** [comment]
Hi wangq,

The new version (5.4.0) should work. Check it out and let me know.

**The issue:** `acccmip6` goes through all available data files and finds the exact realization afterward. But, there is a limit to how many files can be accessed at once. So, for a large number of files, it may miss out on the realization you are looking for. For your case, `acccmip6` needs to access over 45,000 files, which is beyond the initial limit. 

**The fix:** I added a loop search that may take more time but eventually should find all the files you are looking for. For your case it looks like this now:


```
(ac6_env) thassan@DESKTOP-9O8A8FT: acccmip6 -o S -m EC-Earth3 -e historical,ssp126,ssp245,ssp370,ssp585 -v pr -f day -rlzn 1 -dir ~/Downloads/ -skip 1p2,1f2

TIPS: Use the check (-c) argument to check your inputs.

Too many files! Re-constructing for possible missing links . . .

Too many files! Re-constructing for possible missing links . . .

Too many files! Re-constructing for possible missing links . . .

Too many files! Re-constructing for possible missing links . . .

Too many files! Re-constructing for possible missing links . . .

Too many files! Re-constructing for possible missing links . . .

Too many files! Re-constructing for possible missing links . . .

Too many files! Re-constructing for possible missing links . . .

Too many files! Re-constructing for possible missing links . . .

Too many files! Re-constructing for possible missing links . . .

Too many files! Re-constructing for possible missing links . . .

Too many files! Re-constructing for possible missing links . . .

Too many files! Re-constructing for possible missing links . . .

Too many files! Re-constructing for possible missing links . . .

Too many files! Re-constructing for possible missing links . . .

Too many files! Re-constructing for possible missing links . . .

Too many files! Re-constructing for possible missing links . . .


 Currently available models based on your search:

 ['EC-Earth3']

Currently available variables based on your search:

 ['pr']

Currently available experiments based on your search:

 ['ssp370', 'historical', 'ssp585', 'ssp245', 'ssp126']



Number of files: 510



Available realizations: [1]




       <===============Exiting now!================>
```

Downloading (-o D) should work the same way. If you still don't see all the files, try breaking up your search into 2/3 searches. 

Happy downloading~
Taufiq

**Comment by at123456789x** [comment]
Hi Taufiq,

Thanks for your help.

I download such datasets successfully after updating `acccmip6` to version 5.4.0. I tried reinstalling the package before,  but `conda` and `pip` provided version 5.3.0 as default.

Best wishes,
wangq
