### ISSUE TITLE
realization option cannot handle too big realization numbers

### ISSUE THREAD

**Issue by lihansunbai** [TaufiqHassan/acccmip6#2]
Dear Tau

I am using acccmip6 to download historical experiments tas data. However historical experiments have more than 140s realizations and the realization options in acccmip6 cannot handle this amount of realizations, which the `-rlzn 1' option will include realizations like r1i1p1f1, r11i1p1f1 and r1i1p1f1 etc. How could I selected the r1 realizations without r11 realizations for models.  Could this to be bug?

 Sincerely

**Comment by TaufiqHassan** [comment]
Hi, 

Which version are you using? This is a fixed bug in the later versions of acccmip6. Does this issue persist in the latest 5.1.2 (12/2020)? If you are still having issues, use the `-skip` option to skip r11 etc.

Note that the package is designed to download all available first realizations with -rlzn 1 option regardless of the variant (e.g. r1i1p1f1  and r1i1p1f2 and r1i1p2f1). If you do not want to download a certain variant you can always use the 'skip' option. For instance, if you do not want the latter 2 options, add '-skip 1p2,1f2' in your command line. This is also usable for any other case, such as to deal with the grid options. You can use '-skip _gr1_,_gr2_' and so on.

Taufiq

**Comment by lihansunbai** [comment]
Hi,

I finally find the problems were in. Accmip6 fetched the every single file and give the total amount of files of available data rather give the available data of models. So `-rlzn' option could select r1i1p1f1 and aviod r11i1p1f1. And it works well. :)

thanks!
