### ISSUE TITLE
cannot select Table ID

### ISSUE THREAD

**Issue by longbiao1993** [TaufiqHassan/acccmip6#8]
when I downloaded data by selecting  6hrPt Frequency, there are two Tables (6hrPlev and 6hrPlevPt). But I just need 6hrPlevPt. So too many variables will be downloaded, which will take double time.

**Comment by TaufiqHassan** [comment]
Use the skip option. You can skip files with '-skip _6hrPlev_' (should skip all files with _6hrPlev_ in the filename).

Taufiq

**Comment by longbiao1993** [comment]
> 

Thanks, I apply that, Really a nice tool
